/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg:                'var(--color-bg)',
        surface:           'var(--color-surface)',
        'surface-raised':  'var(--color-surface-raised)',
        line:              'var(--color-border)',
        'line-subtle':     'var(--color-border-subtle)',
        ink:               'var(--color-ink)',
        'ink-2':           'var(--color-ink-2)',
        'ink-placeholder': 'var(--color-ink-placeholder)',
        primary:           'var(--color-primary)',
        'primary-hover':   'var(--color-primary-hover)',
        'primary-active':  'var(--color-primary-active)',
        'primary-surface': 'var(--color-primary-surface)',
        'primary-subtle':  'var(--color-primary-subtle)',
        accent:            'var(--color-accent)',
        'accent-on':       'var(--color-accent-on)',
        'accent-ink':      'var(--color-accent-ink)',
        'accent-surface':  'var(--color-accent-surface)',
        success:           'var(--color-success)',
        'success-surface': 'var(--color-success-surface)',
        warning:           'var(--color-warning)',
        'warning-surface': 'var(--color-warning-surface)',
        error:             'var(--color-error)',
        'error-surface':   'var(--color-error-surface)',
        'sb-bg':       'var(--sb-bg)',
        'sb-surface':  'var(--sb-surface)',
        'sb-border':   'var(--sb-border)',
        'sb-ink':      'var(--sb-ink)',
        'sb-ink-2':    'var(--sb-ink-2)',
        'sb-ink-3':    'var(--sb-ink-3)',
        'sb-active-bg':'var(--sb-active-bg)',
        'sb-hover-bg': 'var(--sb-hover-bg)',
        'sb-badge-bg': 'var(--sb-badge-bg)',
        // shadcn-style semantic colors (Tailwind v3 needs these declared so
        // utilities like bg-card / border-border resolve). The values are CSS
        // vars scoped by each ui/ component's own theme class, so they only
        // apply where that class is present.
        background:        'var(--color-background)',
        foreground:        'var(--color-foreground)',
        card:              'var(--color-card)',
        'card-foreground': 'var(--color-card-foreground)',
        muted:             'var(--color-muted)',
        'muted-foreground':'var(--color-muted-foreground)',
        border:            'var(--color-border)',
        ring:              'var(--color-ring)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs:   'var(--text-xs)',
        sm:   'var(--text-sm)',
        base: 'var(--text-base)',
        lg:   'var(--text-lg)',
        xl:   'var(--text-xl)',
        '2xl':'var(--text-2xl)',
        '3xl':'var(--text-3xl)',
      },
      fontWeight: {
        regular:  '400',
        medium:   '500',
        semibold: '600',
        bold:     '700',
      },
      lineHeight: {
        tight:   '1.2',
        snug:    '1.35',
        base:    '1.55',
        relaxed: '1.7',
      },
      spacing: {
        1:  'var(--space-1)',
        2:  'var(--space-2)',
        3:  'var(--space-3)',
        4:  'var(--space-4)',
        5:  'var(--space-5)',
        6:  'var(--space-6)',
        8:  'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
      },
      borderRadius: {
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        low:     'var(--shadow-low)',
        ambient: 'var(--shadow-ambient)',
        lifted:  'var(--shadow-lifted)',
      },
      transitionTimingFunction: {
        'out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'out-quint': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'out-expo':  'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      transitionDuration: {
        fast:  '120ms',
        base:  '200ms',
        slow:  '320ms',
        enter: '280ms',
      },
      zIndex: {
        dropdown:        '100',
        sticky:          '200',
        'modal-backdrop':'300',
        modal:           '400',
        toast:           '500',
        tooltip:         '600',
      },
      maxWidth: {
        content: 'var(--content-width)',
      },
    },
  },
  plugins: [],
}
